#!/bin/bash
set -e

if [ "$#" -ne 2 ]; then
   echo "Must pass a source and a destination file" >&2
   exit 1
fi

sed \
  -e "s|@FLATPAK_ARCH@|${FLATPAK_ARCH}|g" \
  -e "s|@BRANCH@|${BRANCH}|g" \
  $1 > $2
